"""your descriptive message

Revision ID: 1b4c0c8453cd
Revises: 747bea0a3555
Create Date: 2024-02-16 21:33:59.660394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4c0c8453cd'
down_revision = '747bea0a3555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('activity_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_log', schema=None) as batch_op:
        batch_op.alter_column('activity_type',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
